#!/usr/bin/env sh
set -eu

WRANGLER_VERSION="4.135.0"
W="npx --yes wrangler@${WRANGLER_VERSION}"
DOMAIN="https://thebedesk.com"

echo "Thebe Desk V81 Recovery R1 — fresh Cloudflare production launch sequence"
echo "Runtime release: V78 1.21.101 recovered under V81 Recovery R1"
echo "Current reviewed schema delta: 048_v102_bounded_internal_task_execution.sql"
echo "Existing databases must migrate through 048_v102_bounded_internal_task_execution.sql; new Recovery R1 databases load the current schema.sql, then migration 047, then migration 048."
echo "Reviewed Wrangler CLI: ${WRANGLER_VERSION}"
echo "Launch defaults: payments disabled; evidence uploads disabled fail-closed; no third-party scanner configured."
echo ""
echo "1) From the repository root, authenticate Wrangler for the intended production Cloudflare account"
echo "   ${W} login"
echo "2) Create the NEW D1 database"
echo "   ${W} d1 create bw-compliance-os"
echo "3) Record the returned D1 UUID privately; do not commit it"
echo "4) Create the NEW private R2 evidence bucket"
echo "   ${W} r2 bucket create bw-compliance-evidence"
echo "5) Create a NEW Invisible Turnstile widget for the production domain"
echo "   ${W} turnstile widget create 'Thebe Desk Recovery R1' --domain thebedesk.com --mode invisible --json"
echo "6) Record the returned Turnstile site key and secret privately; never commit the secret"
echo "7) cd cloudflare"
echo "8) export D1_DATABASE_ID='<UUID returned by step 2>'"
echo "9) export PUBLIC_APP_URL='${DOMAIN}' && export PUBLIC_ORIGIN=\"\$PUBLIC_APP_URL\""
echo "10) export TURNSTILE_SITE_KEY='<site key returned by step 5>'"
echo "11) export PLATFORM_ADMIN_EMAILS='<verified admin email[,admin2]>'"
echo "12) export PLATFORM_REGULATORY_REVIEWERS='<verified reviewer email[,reviewer2]>'"
echo "13) export GOOGLE_OAUTH_CLIENT_ID='<Google production OAuth client ID>'"
echo "14) export GOOGLE_OAUTH_REDIRECT_URI='${DOMAIN}/api/auth/oauth/google/callback'"
echo "15) export FACEBOOK_APP_ID='<Meta/Facebook production app ID>'"
echo "16) export FACEBOOK_OAUTH_REDIRECT_URI='${DOMAIN}/api/auth/oauth/facebook/callback'"
echo "17) export EMAIL_FROM='Thebe Desk <verified-sender@your-domain>'"
echo "18) unset EVIDENCE_SCAN_API_URL  # evidence uploads are disabled for this launch"
echo "19) Do not configure a malware-scanner provider or EVIDENCE_SCAN_SECRET for this release."
echo "20) export PAYMENT_PROVIDER_OVERRIDE=none  # safe launch default; paid checkout disabled"
echo "21) PROD_CONFIG=\$(mktemp ./.wrangler-production.XXXXXX.toml)"
echo "22) trap 'rm -f \"\$PROD_CONFIG\"' EXIT"
echo "23) ./render-production-config.sh > \"\$PROD_CONFIG\" && chmod 600 \"\$PROD_CONFIG\""
echo "24) ./preflight-production.sh \"\$PROD_CONFIG\""
echo "25) For this NEW D1 only: ${W} d1 execute bw-compliance-os --remote --file=schema.sql --config \"\$PROD_CONFIG\""
echo "25b) For this NEW D1 only: ${W} d1 execute bw-compliance-os --remote --file=migrations/047_v81_delegated_authority.sql --config \"\$PROD_CONFIG\""
echo "25c) For this NEW D1 only: ${W} d1 execute bw-compliance-os --remote --file=migrations/048_v102_bounded_internal_task_execution.sql --config \"\$PROD_CONFIG\""
echo "26) ${W} secret put SESSION_SECRET --config \"\$PROD_CONFIG\""
echo "27) ${W} secret put AUDIT_INTEGRITY_SECRET --config \"\$PROD_CONFIG\""
echo "28) ${W} secret put OPERATIONS_SECRET --config \"\$PROD_CONFIG\""
echo "29) ${W} secret put AUTOMATION_SECRET --config \"\$PROD_CONFIG\""
echo "30) ${W} secret put TURNSTILE_SECRET_KEY --config \"\$PROD_CONFIG\"  # use the matching secret from step 5"
echo "31) ${W} secret put PAYMENT_WEBHOOK_SECRET --config \"\$PROD_CONFIG\""
echo "32) ${W} secret put BILLING_WEBHOOK_SECRET --config \"\$PROD_CONFIG\""
echo "33) ${W} secret put GOOGLE_OAUTH_CLIENT_SECRET --config \"\$PROD_CONFIG\""
echo "34) ${W} secret put FACEBOOK_APP_SECRET --config \"\$PROD_CONFIG\""
echo "35) ${W} secret put RESEND_API_KEY --config \"\$PROD_CONFIG\""
echo "36) Keep PAYMENT_PROVIDER_OVERRIDE=none unless DPO credentials/endpoints are fully verified; only then render a fresh config with PAYMENT_PROVIDER_OVERRIDE=dpo"
echo "37) ./preflight-production.sh \"\$PROD_CONFIG\""
echo "38) ${W} deploy --config \"\$PROD_CONFIG\""
echo "39) Verify /api/live and /api/ready on PUBLIC_ORIGIN; /api/ready must report schemaReady=true, coreSchemaReady=true, agenticAuthoritySchemaReady=true and requiredConfigReady=true"
echo "40) POST an empty JSON body to /api/auth/registration-proof/challenge with Origin: ${DOMAIN}; require provider=thebe_proof, action=register, required=true and a signed challenge token"
echo "41) Verify /api/auth/oauth/google/start redirects to accounts.google.com and /api/auth/oauth/facebook/start redirects to www.facebook.com"
echo "42) Run registration/login, password-reset, tenant-isolation, role, CSRF/origin and launch smoke tests"
echo "43) Verify evidence upload/mutation routes fail closed while EVIDENCE_UPLOADS_ENABLED=false; do not accept evidence bytes until an approved scanner provider is separately integrated and qualified"
echo "44) After live verification, seal the exact GitHub SHA with the fresh BF-07 workflow; do not reuse historical audit/provenance files"
echo ""
echo "The template uses keep_vars=true so optional dashboard variables are preserved; readiness-critical values are rendered only into the ephemeral production config."
echo "Secrets are never written to source control. Google/Facebook OAuth and Resend are launch-required; evidence uploads and payments remain disabled."
echo "Orange Money production activation is blocked until its readiness-key mismatch is separately fixed and reviewed."
echo "This sequence is for a NEW D1. Existing database: DO NOT replay schema.sql. Back up first and apply only reviewed forward-only migrations through 048_v102_bounded_internal_task_execution.sql instead."
