#!/usr/bin/env sh
set -eu

WRANGLER_VERSION="4.127.1"
W="npx --yes wrangler@${WRANGLER_VERSION}"
DOMAIN="https://thebedesk.com"

echo "Thebe Desk V81 Recovery R1 — fresh Cloudflare production launch sequence"
echo "Runtime release: V78 1.21.101 recovered under V81 Recovery R1"
echo "Current reviewed schema delta: 043_v78_session_inventory_hardening.sql"
echo "Existing databases must migrate through 043_v78_session_inventory_hardening.sql; new Recovery R1 databases load the current schema.sql instead."
echo "Reviewed Wrangler CLI: ${WRANGLER_VERSION}"
echo "Safe-launch defaults: payments disabled; evidence uploads disabled until a scanner is configured and re-qualified."
echo ""
echo "1) From the repository root, authenticate Wrangler for the intended production Cloudflare account"
echo "   ${W} login"
echo "2) Create the NEW D1 database"
echo "   ${W} d1 create bw-compliance-os"
echo "3) Record the returned D1 UUID privately; do not commit it"
echo "4) Create the NEW private R2 evidence bucket"
echo "   ${W} r2 bucket create bw-compliance-evidence"
echo "5) Create a NEW Invisible Turnstile widget for the production domain"
echo "   ${W} turnstile widget create 'Thebe Desk Recovery R1' --domain thebedesk.com --mode invisible --json"
echo "6) Record the returned Turnstile site key and secret privately; never commit the secret"
echo "7) cd cloudflare"
echo "8) export D1_DATABASE_ID='<UUID returned by step 2>'"
echo "9) export PUBLIC_APP_URL='${DOMAIN}' && export PUBLIC_ORIGIN=\"\$PUBLIC_APP_URL\""
echo "10) export TURNSTILE_SITE_KEY='<site key returned by step 5>'"
echo "11) export PLATFORM_ADMIN_EMAILS='<verified admin email[,admin2]>'"
echo "12) export PLATFORM_REGULATORY_REVIEWERS='<verified reviewer email[,reviewer2]>'"
echo "13) export EVIDENCE_SCAN_API_URL=''  # Recovery R1 safe launch: evidence uploads remain disabled"
echo "14) export EVIDENCE_UPLOADS_ENABLED_OVERRIDE=false"
echo "15) export PAYMENT_PROVIDER_OVERRIDE=none  # safe launch default; paid checkout disabled"
echo "16) PROD_CONFIG=\$(mktemp ./.wrangler-production.XXXXXX.toml)"
echo "17) trap 'rm -f \"\$PROD_CONFIG\"' EXIT"
echo "18) ./render-production-config.sh > \"\$PROD_CONFIG\" && chmod 600 \"\$PROD_CONFIG\""
echo "19) ./preflight-production.sh \"\$PROD_CONFIG\""
echo "20) For this NEW D1 only: ${W} d1 execute bw-compliance-os --remote --file=schema.sql --config \"\$PROD_CONFIG\""
echo "21) ${W} secret put SESSION_SECRET --config \"\$PROD_CONFIG\""
echo "22) ${W} secret put AUDIT_INTEGRITY_SECRET --config \"\$PROD_CONFIG\""
echo "23) ${W} secret put OPERATIONS_SECRET --config \"\$PROD_CONFIG\""
echo "24) ${W} secret put AUTOMATION_SECRET --config \"\$PROD_CONFIG\""
echo "25) ${W} secret put TURNSTILE_SECRET_KEY --config \"\$PROD_CONFIG\"  # use the matching secret from step 5"
echo "26) ${W} secret put PAYMENT_WEBHOOK_SECRET --config \"\$PROD_CONFIG\""
echo "27) ${W} secret put BILLING_WEBHOOK_SECRET --config \"\$PROD_CONFIG\""
echo "28) EVIDENCE_SCAN_SECRET is intentionally deferred while uploads are disabled. Before enabling uploads, configure EVIDENCE_SCAN_API_URL and run: ${W} secret put EVIDENCE_SCAN_SECRET --config \"\$PROD_CONFIG\""
echo "29) Keep PAYMENT_PROVIDER_OVERRIDE=none unless DPO credentials/endpoints are fully verified; only then render a fresh config with PAYMENT_PROVIDER_OVERRIDE=dpo"
echo "30) Before enabling password reset/email, set RESEND_API_KEY with the same production config and configure a verified EMAIL_FROM"
echo "31) Confirm thebedesk.com is on this Cloudflare account and the Worker custom-domain route is attachable; workers.dev and Preview URLs remain disabled"
echo "32) ./preflight-production.sh \"\$PROD_CONFIG\""
echo "33) ${W} deploy --config \"\$PROD_CONFIG\""
echo "34) Verify /api/live and /api/ready on PUBLIC_ORIGIN; /api/ready must report schemaReady=true and requiredConfigReady=true"
echo "35) Verify /api/auth/anti-bot-config reports provider=turnstile, action=register, required=true and the exact new site key"
echo "36) Run registration/login, tenant-isolation, role, CSRF/origin and launch smoke tests"
echo "37) Evidence quarantine→scan→clean→authorized-download testing is REQUIRED before changing EVIDENCE_UPLOADS_ENABLED from false to true"
echo "38) After live verification, seal the exact GitHub SHA with the fresh BF-07 workflow; do not reuse historical audit/provenance files"
echo ""
echo "The template uses keep_vars=true so optional dashboard variables are preserved; readiness-critical values are rendered only into the ephemeral production config."
echo "Secrets are never written to source control. Recovery R1 deliberately launches fail-closed for evidence uploads and payments."
echo "Orange Money production activation is blocked until its readiness-key mismatch is separately fixed and reviewed."
echo "This sequence is for a NEW D1. Existing database: DO NOT replay schema.sql. Back up first and apply only reviewed forward-only migrations instead."
