// Thebe Desk Phase 1 agent policy.
// This module is deterministic by design: models may propose work, but they may
// never grant themselves permissions or bypass the action catalogue.

export const AGENT_POLICY_VERSION = "2026-09-08.phase1-five-agent";

export const AGENT_ACTION_LEVELS = Object.freeze({ READ: 1, PREPARE: 2, CONTROLLED_EXECUTE: 3, HIGH_RISK: 4 });

export const THEBE_AGENTS = Object.freeze({
  management: Object.freeze({ key:"management", label:"Management Agent", purpose:"Explain governed business health and prepare management briefs from authorised workspace data.", allowedRoles:Object.freeze(["owner","manager"]) }),
  compliance: Object.freeze({ key:"compliance", label:"Compliance Agent", purpose:"Explain verified obligations and risks and prepare compliance follow-up for human review.", allowedRoles:Object.freeze(["owner","manager","reviewer"]) }),
  tender: Object.freeze({ key:"tender", label:"Tender Readiness Agent", purpose:"Assess tender readiness and prepare evidence/checklist packs without claiming eligibility or award.", allowedRoles:Object.freeze(["owner","manager","reviewer"]) }),
  operations: Object.freeze({ key:"operations", label:"Daily Operations Agent", purpose:"Summarise aggregate operational signals without exposing employee reports or enabling surveillance.", allowedRoles:Object.freeze(["owner","manager"]) }),
  finance: Object.freeze({ key:"finance", label:"Finance Agent", purpose:"Explain reconciled Finance Core outputs and prepare finance briefs without inventing numbers, posting ledger entries or moving money.", allowedRoles:Object.freeze(["owner","manager","reviewer"]) })
});

function action({key,level,agents,roles,description,phase1Enabled,humanReviewRequired=false,explicitApprovalRequired=false,strongAuthRequired=false,externalSideEffect=false,sensitiveDomain=null,authoritativeSource=null}) {
  return Object.freeze({key,level,agents:Object.freeze([...agents]),roles:Object.freeze([...roles]),description,phase1Enabled:Boolean(phase1Enabled),humanReviewRequired:Boolean(humanReviewRequired),explicitApprovalRequired:Boolean(explicitApprovalRequired),strongAuthRequired:Boolean(strongAuthRequired),externalSideEffect:Boolean(externalSideEffect),sensitiveDomain,authoritativeSource});
}

export const AGENT_ACTION_CATALOG = Object.freeze({
  "business_health.read": action({key:"business_health.read",level:AGENT_ACTION_LEVELS.READ,agents:["management"],roles:["owner","manager"],description:"Read governed business-health indicators and recorded risks.",phase1Enabled:true,authoritativeSource:"business_graph_and_deterministic_metrics"}),
  "compliance_status.read": action({key:"compliance_status.read",level:AGENT_ACTION_LEVELS.READ,agents:["compliance"],roles:["owner","manager","reviewer"],description:"Read current verified obligations, status and approved source references.",phase1Enabled:true,authoritativeSource:"country_rules_and_verified_workspace_records"}),
  "compliance_risk.explain": action({key:"compliance_risk.explain",level:AGENT_ACTION_LEVELS.READ,agents:["compliance"],roles:["owner","manager","reviewer"],description:"Explain a recorded compliance risk and its evidence/source references.",phase1Enabled:true,authoritativeSource:"country_rules_and_verified_workspace_records"}),
  "tender_readiness.read": action({key:"tender_readiness.read",level:AGENT_ACTION_LEVELS.READ,agents:["tender"],roles:["owner","manager","reviewer"],description:"Read active tender readiness and mandatory evidence gaps without promising eligibility or award.",phase1Enabled:true,authoritativeSource:"verified_tender_and_evidence_records"}),
  "daily_operations_summary.read": action({key:"daily_operations_summary.read",level:AGENT_ACTION_LEVELS.READ,agents:["operations"],roles:["owner","manager"],description:"Read aggregate Daily Operations metrics only; never expose employee report narratives.",phase1Enabled:true,sensitiveDomain:"workforce_aggregate",authoritativeSource:"aggregate_daily_operations_metrics"}),
  "financial_position.read": action({key:"financial_position.read",level:AGENT_ACTION_LEVELS.READ,agents:["finance"],roles:["owner","manager","reviewer"],description:"Read reconciled cash, receivables, payables, income and expense outputs from the Finance Core without inventing values.",phase1Enabled:true,sensitiveDomain:"finance",authoritativeSource:"reconciled_finance_core"}),
  "management_accounts.read": action({key:"management_accounts.read",level:AGENT_ACTION_LEVELS.READ,agents:["finance"],roles:["owner","manager","reviewer"],description:"Read generated management-account outputs and their period/provenance metadata.",phase1Enabled:true,sensitiveDomain:"finance",authoritativeSource:"reconciled_finance_core"}),
  "finance_data_quality.read": action({key:"finance_data_quality.read",level:AGENT_ACTION_LEVELS.READ,agents:["finance"],roles:["owner","manager","reviewer"],description:"Read reconciliation, completeness and provenance indicators used to qualify finance conclusions.",phase1Enabled:true,sensitiveDomain:"finance",authoritativeSource:"finance_data_quality_controls"}),
  "management_brief.prepare": action({key:"management_brief.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["management"],roles:["owner","manager"],description:"Prepare a management brief as a draft for human review.",phase1Enabled:true,humanReviewRequired:true,authoritativeSource:"business_graph_and_deterministic_metrics"}),
  "compliance_action_plan.prepare": action({key:"compliance_action_plan.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["compliance"],roles:["owner","manager","reviewer"],description:"Prepare a compliance action plan from verified rules and recorded workspace facts.",phase1Enabled:true,humanReviewRequired:true,authoritativeSource:"country_rules_and_verified_workspace_records"}),
  "evidence_request.prepare": action({key:"evidence_request.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["compliance","tender"],roles:["owner","manager","reviewer"],description:"Prepare, but do not send, an evidence request for human review.",phase1Enabled:true,humanReviewRequired:true,authoritativeSource:"verified_workspace_records"}),
  "tender_pack.prepare": action({key:"tender_pack.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["tender"],roles:["owner","manager","reviewer"],description:"Prepare a tender-readiness evidence/checklist pack for human review.",phase1Enabled:true,humanReviewRequired:true,authoritativeSource:"verified_tender_and_evidence_records"}),
  "daily_operations_brief.prepare": action({key:"daily_operations_brief.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["operations"],roles:["owner","manager"],description:"Prepare an aggregate operations brief without employee surveillance or disciplinary recommendations.",phase1Enabled:true,humanReviewRequired:true,sensitiveDomain:"workforce_aggregate",authoritativeSource:"aggregate_daily_operations_metrics"}),
  "finance_brief.prepare": action({key:"finance_brief.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["finance"],roles:["owner","manager","reviewer"],description:"Prepare a finance brief from reconciled Finance Core outputs, explicitly carrying period, data-quality and provenance qualifiers.",phase1Enabled:true,humanReviewRequired:true,sensitiveDomain:"finance",authoritativeSource:"reconciled_finance_core"}),
  "journal_entry.prepare": action({key:"journal_entry.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["finance"],roles:["owner","manager","reviewer"],description:"Reserved journal-entry draft action; disabled until ledger evidence-linking and accountant review controls are production-ready.",phase1Enabled:false,humanReviewRequired:true,sensitiveDomain:"finance_ledger",authoritativeSource:"reconciled_finance_core"}),
  "filing_draft.prepare": action({key:"filing_draft.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["compliance"],roles:["owner","manager","reviewer"],description:"Reserved filing-draft action; disabled until country-rule and form-specific validation is complete.",phase1Enabled:false,humanReviewRequired:true,sensitiveDomain:"regulatory_filing",authoritativeSource:"country_rules_and_verified_workspace_records"}),
  "payroll_draft.prepare": action({key:"payroll_draft.prepare",level:AGENT_ACTION_LEVELS.PREPARE,agents:["finance"],roles:["owner","manager"],description:"Reserved payroll-draft action; disabled because payroll remains outside the launch Finance Core boundary.",phase1Enabled:false,humanReviewRequired:true,sensitiveDomain:"payroll",authoritativeSource:"approved_payroll_integration"}),
  "task.create": action({key:"task.create",level:AGENT_ACTION_LEVELS.CONTROLLED_EXECUTE,agents:["management","compliance","tender","operations","finance"],roles:["owner","manager"],description:"Create an internal task through controlled execution.",phase1Enabled:false}),
  "document.request": action({key:"document.request",level:AGENT_ACTION_LEVELS.CONTROLLED_EXECUTE,agents:["compliance","tender","finance"],roles:["owner","manager"],description:"Send a controlled document request.",phase1Enabled:false,externalSideEffect:true}),
  "reminder.send": action({key:"reminder.send",level:AGENT_ACTION_LEVELS.CONTROLLED_EXECUTE,agents:["management","compliance","tender","operations","finance"],roles:["owner","manager"],description:"Send a controlled reminder through an approved notification channel.",phase1Enabled:false,externalSideEffect:true}),
  "approval.create": action({key:"approval.create",level:AGENT_ACTION_LEVELS.CONTROLLED_EXECUTE,agents:["management","compliance","tender","operations","finance"],roles:["owner","manager"],description:"Create an internal approval request without performing the underlying high-risk action.",phase1Enabled:false}),
  "journal_entry.post": action({key:"journal_entry.post",level:AGENT_ACTION_LEVELS.CONTROLLED_EXECUTE,agents:["finance"],roles:["owner","manager"],description:"Post an approved journal entry to the Finance Core.",phase1Enabled:false,sensitiveDomain:"finance_ledger",authoritativeSource:"reconciled_finance_core"}),
  "payment.execute": action({key:"payment.execute",level:AGENT_ACTION_LEVELS.HIGH_RISK,agents:["management","finance"],roles:["owner"],description:"Reserved high-risk payment execution.",phase1Enabled:false,explicitApprovalRequired:true,strongAuthRequired:true,externalSideEffect:true,sensitiveDomain:"payments"}),
  "government_filing.submit": action({key:"government_filing.submit",level:AGENT_ACTION_LEVELS.HIGH_RISK,agents:["compliance"],roles:["owner"],description:"Reserved high-risk government filing submission.",phase1Enabled:false,explicitApprovalRequired:true,strongAuthRequired:true,externalSideEffect:true,sensitiveDomain:"regulatory_filing"}),
  "document.sign": action({key:"document.sign",level:AGENT_ACTION_LEVELS.HIGH_RISK,agents:["management","compliance","tender","finance"],roles:["owner"],description:"Reserved high-risk signature action.",phase1Enabled:false,explicitApprovalRequired:true,strongAuthRequired:true,externalSideEffect:true,sensitiveDomain:"signature"}),
  "employment.terminate": action({key:"employment.terminate",level:AGENT_ACTION_LEVELS.HIGH_RISK,agents:["management"],roles:["owner"],description:"Reserved employment termination action. The agent may never autonomously decide termination.",phase1Enabled:false,explicitApprovalRequired:true,strongAuthRequired:true,externalSideEffect:true,sensitiveDomain:"employment"}),
  "financing.accept": action({key:"financing.accept",level:AGENT_ACTION_LEVELS.HIGH_RISK,agents:["management","finance"],roles:["owner"],description:"Reserved high-risk financing acceptance action.",phase1Enabled:false,explicitApprovalRequired:true,strongAuthRequired:true,externalSideEffect:true,sensitiveDomain:"financing"})
});

function deny(code,reason,actionDefinition=null){return Object.freeze({allowed:false,decision:"deny",code,reason,policyVersion:AGENT_POLICY_VERSION,action:actionDefinition,humanReviewRequired:Boolean(actionDefinition?.humanReviewRequired),explicitApprovalRequired:Boolean(actionDefinition?.explicitApprovalRequired),strongAuthRequired:Boolean(actionDefinition?.strongAuthRequired),externalSideEffect:Boolean(actionDefinition?.externalSideEffect)})}

export function evaluateAgentAction({agentKey,actionKey,actorRole,tenantScoped=false,strongAuth=false,approvalState="none",phase="phase1"}={}){
  const agent=THEBE_AGENTS[String(agentKey||"")]; if(!agent)return deny("unknown_agent","Unknown agent; policy fails closed.");
  const definition=AGENT_ACTION_CATALOG[String(actionKey||"")]; if(!definition)return deny("unknown_action","Unknown action; policy fails closed.");
  if(tenantScoped!==true)return deny("tenant_scope_required","Agent actions require an authenticated tenant scope.",definition);
  const role=String(actorRole||"").trim().toLowerCase();
  if(!definition.agents.includes(agent.key))return deny("agent_action_mismatch","This agent is not authorised for the requested action.",definition);
  if(!agent.allowedRoles.includes(role)||!definition.roles.includes(role))return deny("role_forbidden","The current role is not authorised for this agent action.",definition);
  if(phase!=="phase1"||definition.phase1Enabled!==true)return deny("action_not_enabled","The action is not enabled in the current launch phase.",definition);
  if(definition.level===AGENT_ACTION_LEVELS.HIGH_RISK){
    if(definition.explicitApprovalRequired&&approvalState!=="approved")return deny("explicit_approval_required","Explicit human approval is required.",definition);
    if(definition.strongAuthRequired&&strongAuth!==true)return deny("strong_auth_required","Strong authentication is required.",definition);
  }
  if(definition.externalSideEffect)return deny("external_side_effect_not_enabled","Phase 1 agents cannot perform external side effects.",definition);
  const prepareOnly=definition.level===AGENT_ACTION_LEVELS.PREPARE;
  return Object.freeze({allowed:true,decision:prepareOnly?"prepare_only":"allow_read",code:prepareOnly?"human_review_required":"allowed",reason:prepareOnly?"The agent may create a bounded draft, but a human must review it before any downstream action.":"The read is permitted within the authenticated tenant and role scope.",policyVersion:AGENT_POLICY_VERSION,action:definition,humanReviewRequired:prepareOnly||definition.humanReviewRequired,explicitApprovalRequired:definition.explicitApprovalRequired,strongAuthRequired:definition.strongAuthRequired,externalSideEffect:false});
}
export function listPhase1AgentActions(agentKey,actorRole){const agent=THEBE_AGENTS[String(agentKey||"")],role=String(actorRole||"").trim().toLowerCase();if(!agent||!agent.allowedRoles.includes(role))return[];return Object.values(AGENT_ACTION_CATALOG).filter(d=>d.phase1Enabled===true&&d.agents.includes(agent.key)&&d.roles.includes(role)&&d.externalSideEffect===false)}
